# Server
server.port=8088
server.servlet.context-path=/course-management

spring.application.name=course-management

spring.datasource.url=jdbc:mysql://localhost:3306/course_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=dev123@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Kafka
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# JWT
jwt.signerKey=D0iwggWH/ZIxH2ZqhGNlJ8DtjECo2jiiDLU7Dg5bm94hjHCbS8wMK9MyJLCYJCyi
jwt.valid-duration=3600
jwt.refreshable-duration=36000

# Service URLs
app.services.identity=${IDENTITY_SERVICE_URL:http://localhost:8080/identity}

logging.level.com.hoangphihiep=DEBUG
logging.level.org.springframework.web=DEBUG
