spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:root@mongodb:27017/notification_db?authSource=admin}
      auto-index-creation: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# self-defined configs
openapi:
  services:
    api-docs: api-docs
    server: http://api-gateway:8888/api/v1${server.servlet.context-path}
    title: Chat App APIs
    version: 1.0.0
    license:
      name: Apache 2.0
      url: https://springdoc.org

jwt:
  secretKey: D0iwggWH/ZIxH2ZqhGNlJ8DtjECo2jiiDLU7Dg5bm94hjHCbS8wMK9MyJLCYJCyi

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

app:
  file:
    max-size: 10485760 # 10 MB

server:
  port: 8090
  servlet:
    context-path: /server

services:
  identity:
    url: ${SERVICES_IDENTITY_URL:http://identity-service:8080/identity}

rabbitmq:
  exchange:
    name: notification.exchange
  routing:
    key: notification.routingkey
  queue:
    edu-unit-queue: edu-unit-queue

management:
  endpoints:
    web:
      exposure:
        include: health,info  # hoặc "*" nếu muốn expose tất cả
  endpoint:
    health:
      show-details: always