# chat-service
spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@hackathon.n5sib2v.mongodb.net/workspace_db?retryWrites=true&w=majority&appName=Hackathon
      auto-index-creation: true
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      group-id: myGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  servlet:
    multipart:
      max-file-size: 20MB # 10MB = 10 * 1024 * 1024 bytes
      max-request-size: 200MB

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# self-defined configs
openapi:
  services:
    api-docs: api-docs
    server: ${API_GATEWAY_URL:http://localhost:8888}/api/v1${server.servlet.context-path}
    title: Chat App APIs
    version: 1.0.0
    license:
      name: Apache 2.0
      url: https://springdoc.org

jwt:
  secretKey: D0iwggWH/ZIxH2ZqhGNlJ8DtjECo2jiiDLU7Dg5bm94hjHCbS8wMK9MyJLCYJCyi

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

app:
  file:
    max-size: 20971520 # 20MB = 2 * 10 * 1024 * 1024 bytes

server:
  port: 8090
  servlet:
    context-path: /server

services:
  identity:
    url: ${SERVICES_IDENTITY_URL:http://localhost:8080/identity}
  notification:
    url: ${SERVICES_NOTIFICATION_URL:http://localhost:8092}

kafka:
  topic:
    course-events: course-events
    class-events: class-events

management:
  endpoints:
    web:
      exposure:
        include: health,info # hoặc "*" nếu muốn expose tất cả
  endpoint:
    health:
      show-details: always
