spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/workspace_db?authSource=admin
      database: workspace_db
      auto-index-creation: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# self-defined configs
openapi:
  services:
    api-docs: workspace-api-docs
    server: http://localhost:${server.port}
    title: Chat App APIs
    version: 1.0.0
    license:
      name: Apache 2.0
      url: https://springdoc.org

jwt:
  secretKey: XrlXd50JgElviZ+G7WjSvJiMMapYK+vznAV/CUPSGvvLgsB/898dipwLOvGECplI

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

server:
  port: 8090
  servlet:
    context-path: /server

services:
  identity:
    url: http://localhost:8080/identity
