version: "3.8"
services:


  mongodb:
    image: "mongo:7.0-jammy"
    container_name: mongo_notification
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: notification_db
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: realtime-service
    ports:
      - "8090:8090"
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@mongodb:27017/notification_db?authSource=admin
    restart: unless-stopped

volumes:
  mongo_data: