services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"

  mongodb:
    image: "mongo:7.0-jammy"
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "27017:27017"

  redis:
    image: "redis:latest"
    container_name: redis_server
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch_server
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - backend-network
    ports:
      - "5601:5601"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - backend-network
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xms512M -Xmx512M"
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "kafka:29092" ]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "9092:9092"

  identity-service:
    image: ${DOCKERHUB_USER}/identity-service:${VERSION:-latest}
    container_name: identity-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/identity_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SIGNER_KEY: ${JWT_SIGNER_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      FACEBOOK_CLIENT_ID: ${FACEBOOK_CLIENT_ID}
      FACEBOOK_CLIENT_SECRET: ${FACEBOOK_CLIENT_SECRET}
      GOOGLE_AUTH_URI: ${GOOGLE_AUTH_URI}
      GOOGLE_OAUTH_REDIRECT_URL: ${GOOGLE_OAUTH_REDIRECT_URL}
      FACEBOOK_AUTH_URI: ${FACEBOOK_AUTH_URI}
      FACEBOOK_OAUTH_REDIRECT_URL: ${FACEBOOK_OAUTH_REDIRECT_URL}
      OAUTH_REDIRECT_URL: ${OAUTH_REDIRECT_URL}
      PROFILE_SERVICE_URL: http://api-gateway:8888/api/v1/profile
      FILE_SERVICE_URL: http://file-service:8084/file-handler
      COURSE_MANAGEMENT_URL: http://course-service:8088/course-management
      API_GATEWAY_URL: http://api-gateway:8888

      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080/identity/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

  course-service:
    image: ${DOCKERHUB_USER}/course-service:${VERSION:-latest}
    container_name: course-service
    restart: unless-stopped
    environment:
      DB_URL: jdbc:mysql://mysql:3306/course_management?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SIGNER_KEY: ${JWT_SIGNER_KEY}

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

      APP_EMAIL_FROM: ${APP_EMAIL_FROM}
      APP_EMAIL_FROM_NAME: ${APP_EMAIL_FROM_NAME}

      IDENTITY_SERVICE_URL: http://identity-service:8080/identity
      FILE_SERVICE_URL: http://file-service:8084/file-handler
      APP_SERVICES_FILE: http://file-service:8084/file-handler
      API_GATEWAY_URL: http://api-gateway:8888
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      ELASTICSEARCH_URIS: http://elasticsearch:9200
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200

      VNPAY_TMN_CODE: ${VNPAY_TMN_CODE}
      VNPAY_HASH_SECRET: ${VNPAY_HASH_SECRET}
      VNPAY_PAY_URL: ${VNPAY_PAY_URL}
      VNPAY_RETURN_URL: ${VNPAY_RETURN_URL}
      VNPAY_API_URL: ${VNPAY_API_URL}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}
      PAYPAL_RETURN_URL: ${PAYPAL_RETURN_URL}
      PAYPAL_CANCEL_URL: ${PAYPAL_CANCEL_URL}
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8088/course-management/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

  file-service:
    image: ${DOCKERHUB_USER}/file-service:${VERSION:-latest}
    container_name: file-service
    restart: unless-stopped
    ports:
      - "8084:8084"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:${MONGO_ROOT_PASSWORD}@mongodb:27017/file-handler-service?authSource=admin
      CLOUDINARY_CLOUD_NAME: ${FILE_SERVICE_CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${FILE_SERVICE_CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${FILE_SERVICE_CLOUDINARY_API_SECRET}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8084/file-handler/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

  chat-service:
    image: ${DOCKERHUB_USER}/chat-service:${VERSION:-latest}
    container_name: chat-service
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:${MONGO_ROOT_PASSWORD}@mongodb:27017/mongo_notification?authSource=admin
      JWT_SECRET_KEY: ${JWT_SIGNER_KEY}
      CLOUDINARY_CLOUD_NAME: ${CHAT_SERVICE_CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CHAT_SERVICE_CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CHAT_SERVICE_CLOUDINARY_API_SECRET}
      SERVICES_IDENTITY_URL: http://identity-service:8080/identity
      API_GATEWAY_URL: http://api-gateway:8888
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      MONGO_DB_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8090/server/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

  api-gateway:
    image: ${DOCKERHUB_USER}/api-gateway:${VERSION:-latest}
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: production
      IDENTITY_SERVICE_URI: http://identity-service:8080
      PROFILE_SERVICE_URI: http://profile-service:8081
      FILE_SERVICE_URI: http://file-service:8084
      COURSE_SERVICE_URI: http://course-service:8088
      CHAT_SERVICE_URI: http://chat-service:8090
      CHAT_SERVICE_WS_URI: ws://chat-service:8090
    depends_on:
      identity-service:
        condition: service_healthy
      course-service:
        condition: service_healthy
      file-service:
        condition: service_healthy
      chat-service:
        condition: service_healthy
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8888/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

volumes:
  es-data:
  mysql_data:
    driver: local
  mongo_data:
    driver: local
  redis_data:
    driver: local

networks:
  backend-network:
    driver: bridge