server:
  port: 8080
  servlet:
    context-path: /identity

# self-defined configs
openapi:
  services:
    api-docs: api-docs
    server: http://localhost:8888/api/v1${server.servlet.context-path}
    title: Identity Service APIs
    version: 1.0.0
    license:
      name: Apache 2.0
      url: https://springdoc.org

spring:
  application:
    name: identity-service
  datasource:
    url: "${DB_URL:jdbc:mysql://localhost:3306/identity_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: "${FACEBOOK_CLIENT_ID}"
            client-secret: "${FACEBOOK_CLIENT_SECRET}"
            redirect-uri: "${OAUTH_REDIRECT_URL:http://localhost:3000/oauth2/callback/facebook}"
            scope:
              - email
              - public_profile
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  servlet:
    multipart:
      max-file-size: 10MB # 10MB = 10 * 1024 * 1024 bytes
      max-request-size: 100MB

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: "${REDIS_PASSWORD}"
      timeout: 6000 # in milliseconds


jwt:
  signerKey: "${JWT_SIGNER_KEY}"
  valid-duration: 600 # in second around 10 minutes
  refreshable-duration: 86400 # in seconds around a day

outbound:
  google:
    auth-uri: "${GOOGLE_AUTH_URI:https://accounts.google.com/o/oauth2/v2/auth}"
    client-id: "${GOOGLE_CLIENT_ID}"
    client-secret: "${GOOGLE_CLIENT_SECRET}"
    callback-url: "${GOOGLE_OAUTH_REDIRECT_URL:http://localhost:3000/auth/google/callback}"
  facebook:
    auth-uri: "${FACEBOOK_AUTH_URI:https://www.facebook.com/v24.0/dialog/oauth}"
    client-id: "${FACEBOOK_CLIENT_ID}"
    client-secret: "${FACEBOOK_CLIENT_SECRET}"
    callback-url: "${FACEBOOK_OAUTH_REDIRECT_URL:http://localhost:3000/auth/facebook/callback}"

app:
  services:
    profile: "${PROFILE_SERVICE_URL:http://localhost:8081/profile}"
    file: "${FILE_SERVICE_URL:http://localhost:8084/file-handler}"
    course: "${COURSE_MANAGEMENT_URL:http://localhost:8088/course-management}"
