spring:
  application:
    name: ai-service

server:
  port: 8000

ai:
  service:
    document-parser: http://localhost:8001/api/v1/parser
    flashcard: http://localhost:8002/api/v1/parser
    quiz: http://localhost:8003/api/v1/quiz
