server:
  port: 8092

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@hackathon.n5sib2v.mongodb.net/notification_service?retryWrites=true&w=majority&appName=Hackathon
      auto-index-creation: true
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:user}
    password: ${SMTP_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
  email:
    from: ${APP_EMAIL_FROM:noreply@example.com}
    from-name: ${APP_EMAIL_FROM_NAME:E-Learning System}
