server:
  port: 8084
  servlet:
    context-path: /file-handler

spring:
  application:
    name: file-handler-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:root@mongodb:27017/file-handler-service?authSource=admin}
  servlet:
    multipart:
      max-file-size: 10MB # 10MB = 10 * 1024 * 1024 bytes
      max-request-size: 100MB

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info  # hoặc * nếu bạn muốn expose hết
  endpoint:
    health:
      show-details: always