# file-service
server:
  port: 8084
  servlet:
    context-path: /file-handler

# self-defined configs
openapi:
  services:
    api-docs: api-docs
    server: ${API_GATEWAY_URL:http://localhost:8888}/api/v1${server.servlet.context-path}
    title: File Service APIs
    version: 1.0.0
    license:
      name: Apache 2.0
      url: https://springdoc.org

spring:
  application:
    name: file-handler-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb+srv://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@hackathon.n5sib2v.mongodb.net/file_db?retryWrites=true&w=majority&appName=Hackathon}
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 20MB # 20MB = 2 * 10 * 1024 * 1024 bytes
      max-request-size: 200MB

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

app:
  services:
    course: "${COURSE_MANAGEMENT_URL:http://localhost:8088/course-management}"

management:
  endpoints:
    web:
      exposure:
        include: health,info  # hoặc * nếu bạn muốn expose hết
  endpoint:
    health:
      show-details: always