# Server
server.port=8088
server.servlet.context-path=/course-management

spring.application.name=course-management

springdoc.api-docs.enabled=true
springdoc.swagger-ui.csrf.enabled=true

openapi.services.api-docs=api-docs
openapi.services.server=http://localhost:8888/api/v1${server.servlet.context-path}
openapi.services.title=Course Management APIs
openapi.services.version=1.0.0
openapi.services.license.name=Apache 2.0
openapi.services.license.url=https://springdoc.org

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Kafka
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# JWT
jwt.signerKey=${JWT_SIGNER_KEY}
jwt.valid-duration=3600
jwt.refreshable-duration=36000

# SendGrid
sendgrid.api.key=${SENDGRID_API_KEY}
app.email.from=${APP_EMAIL_FROM}
app.email.from-name=${APP_EMAIL_FROM_NAME}

# Service URLs
app.services.identity=${IDENTITY_SERVICE_URL:http://localhost:8080/identity}

logging.level.com.hoangphihiep=DEBUG
logging.level.org.springframework.web=DEBUG

# DISABLE standard multipart - chuy?n sang CommonsMultipartResolver

# Multipart configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.location=${java.io.tmpdir}

# Tomcat specific (n?u không dùng Bean config)
server.tomcat.max-http-form-post-size=104857600

##
spring.elasticsearch.uris=http://localhost:9200
# elasticsearch custom values
elasticsearch.host=localhost
elasticsearch.port=9200